- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: Update Brew
      homebrew:
        update_homebrew: true
        state: present
      tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/dotfiles.yml

